#<<<コンテキストをシェルコマンドへ直接埋め込むのはアンチパターンです>>>
#→コンテキストによっては特殊文字が含まれ、シェルコマンドの実行に意図しない影響を与える恐れがあります
#→中間環境変数を利用しましょう
name: Context
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}" #githubコンテキストからワークフロー実行者を参照